name: Build and Test

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

# We only care about the latest revision of a PR, so cancel all previous instances.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        compiler: [
            { cc: "gcc-13", cxx: "g++-13"},
            { cc: "clang-16", cxx: "clang++-16"}
          ]

    name: Build ${{ matrix.os }} with ${{ matrix.compiler.cc }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install LLVM 16
        run: |
          sudo mkdir -p /etc/apt/trusted.gpg.d
          curl -sL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
          sudo apt update

          sudo apt install llvm-16 llvm-16-dev llvm-16-tools clang-16 clang-tidy-16 clang-tools-16 libclang-16-dev -y

      - name: Install GCC 13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install gcc-13 g++-13 -y

      - name: Install Ninja
        run: |
          sudo apt update
          sudo apt install ninja-build -y

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install \
            lua5.3 liblua5.3-dev \
            libglfw3 libglfw3-dev \
            libglew-dev \
            libglm-dev \
            libomp.dev

      - name: Build
        run: |
          mkdir -p build
          cd build

          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
