name: Build and Test

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

# We only care about the latest revision of a PR, so cancel all previous instances.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        compiler: [
            { cc: "gcc", cxx: "g++"},
            { cc: "clang", cxx: "clang++"}
          ]

    name: Build ${{ matrix.os }} with ${{ matrix.compiler.cc }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Ninja
        run: |
          sudo apt update
          sudo apt install ninja-build -y

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install \
            lua5.3 liblua5.3-dev \
            libglfw3 libglfw3-dev \
            libglew-dev \
            libglm-dev \
            libomp-17-dev \
            libpng-dev


      - name: Build
        run: |
          mkdir -p build
          cd build

          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Test
        run: |
          cd build
          ninja test
