name: Build and Test

on:
  push:
    branches: [ 'main', 'Ubuntu-Update' ]

  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

# We only care about the latest revision of a PR, so cancel all previous instances.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        compiler: [
            { cc: "gcc", cxx: "g++"},
            { cc: "clang-19", cxx: "clang++-19"}
          ]
        build:
            - Release
            - Debug

    name: Build ${{ matrix.os }} with ${{ matrix.compiler.cc }} (${{ matrix.build }})
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      ACTION_ENV_CMAKE_BUILD_TYPE: ${{ matrix.build}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Ninja & Clang-19
        run: |
          sudo apt update
          sudo apt install ninja-build -y
          sudo apt install clang-19 -y

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install \
            libglfw3 libglfw3-dev \
            libglew-dev \
            libglm-dev \
            libomp-17-dev \
            libpng-dev


      - name: Build
        run: |
          mkdir -p build
          cd build

          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=$ACTION_ENV_CMAKE_BUILD_TYPE
          cmake --build .

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
            run: ninja test
            working-directory: ./build