name: Build-Test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: |
          cd build
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          ninja