name: Build-Test

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

# We only care about the latest revision of a PR, so cancel all previous instances.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: |
          cd build
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          ninja